# config.py

SYMBOLS = {
    "INDICES": {
        "NIFTY": "^NSEI",
        "BANKNIFTY": "^NSEBANK",
        "SENSEX": "^BSESN"
    },
    "NIFTY50": [
        "RELIANCE.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", "TCS.NS",
        "HINDUNILVR.NS", "ITC.NS", "KOTAKBANK.NS", "SBIN.NS", "BHARTIARTL.NS",
        "ASIANPAINT.NS", "HCLTECH.NS", "MARUTI.NS", "AXISBANK.NS", "LT.NS",
        "BAJFINANCE.NS", "WIPRO.NS", "SUNPHARMA.NS", "ULTRACEMCO.NS",
        "NESTLEIND.NS", "NTPC.NS", "POWERGRID.NS", "M&M.NS", "JSWSTEEL.NS",
        "TITAN.NS", "TATASTEEL.NS", "INDUSINDBK.NS", "ONGC.NS",
        "TATAMOTORS.NS", "ADANIENT.NS", "BAJAJFINSV.NS", "HINDALCO.NS",
        "GRASIM.NS", "CIPLA.NS", "DRREDDY.NS", "TECHM.NS", "ADANIPORTS.NS",
        "BRITANNIA.NS", "EICHERMOT.NS", "UPL.NS", "APOLLOHOSP.NS",
        "HEROMOTOCO.NS", "BPCL.NS", "COALINDIA.NS", "DIVISLAB.NS",
        "SHREECEM.NS", "BAJAJ-AUTO.NS", "TATACONSUM.NS"
    ],
    "MIDCAP": []
}
